"""The benchmark is itself under test.

Two jobs here. First, the committed suite must actually pass and match the
committed scoreboard - this is the numeric CI gate: `pytest` runs it on every
PR, so a harness change that regresses a decision cannot merge. Second, the
scoring machinery must be trustworthy: a malformed scenario is refused rather
than silently counted as a pass, a wrong expectation fails, and an inverted
branch of `decide_path` is caught by name.
"""
from __future__ import annotations

import json
from dataclasses import replace
from pathlib import Path

import pytest
import yaml

from hsai import bench, orchestrator, review
from hsai.cli import main
from hsai.config import load_config

ROOT = Path(__file__).resolve().parents[1]
CORE = ROOT / ".ai-swarm" / "core.yaml"

# What a replay is allowed to invoke. `hsai bench` answers all of these from
# the transcript; nothing may reach a real shell, and nothing may reach the
# network.
ALLOWED_BINARIES = {"git", "gh", "ruff", "pytest", "claude"}

VALID_DOC = {
    "name": "sample",
    "description": "A minimal, valid scenario used to test the loader.",
    "expect": {"path": "improve", "guards": [], "outcome": "merged"},
}


@pytest.fixture(scope="module")
def scenarios() -> list[bench.Scenario]:
    return bench.load_scenarios(ROOT / bench.DEFAULT_SCENARIO_DIR, repo_root=ROOT)


@pytest.fixture(scope="module")
def suite(scenarios) -> bench.SuiteResult:
    return bench.run_suite(scenarios, load_config(CORE))


# --- the gate ---------------------------------------------------------------


def test_the_frozen_suite_passes_and_matches_the_committed_scoreboard(suite):
    assert [(s.scenario, s.reason()) for s in suite.failures()] == []
    assert suite.total >= 8                      # ticket floor for the suite size

    baseline = bench.load_baseline(ROOT / bench.DEFAULT_BASELINE)
    assert bench.check_baseline(suite, baseline) == []

    # The board is regenerated by the command, so the committed copy must be
    # byte-identical to what a fresh run produces.
    committed = (ROOT / bench.DEFAULT_SCOREBOARD).read_text(encoding="utf-8")
    assert committed == bench.render_scoreboard(suite, baseline)


def test_a_regressed_aggregate_or_a_deleted_scenario_trips_the_baseline(suite):
    strict = {"min_aggregate_score": 1.0, "min_scenarios": suite.total + 1}
    problems = bench.check_baseline(suite, strict)
    assert problems and "below the committed baseline of" in problems[0]

    # Aggregate regression is reported separately from suite shrinkage.
    shrunk = bench.SuiteResult(
        scores=[bench.ScenarioScore("x", checks=[bench.Check("path", "heal", "improve")])],
        scenarios=[],
    )
    assert shrunk.aggregate == 0.0
    assert len(bench.check_baseline(shrunk, {"min_aggregate_score": 1.0, "min_scenarios": 2})) == 2


def test_every_scenario_replays_offline(suite):
    for score in suite.scores:
        assert set(score.binaries) <= ALLOWED_BINARIES, score.scenario
    # The budget-halt scenario refuses to start work at all, so it spawns nothing.
    halted = next(s for s in suite.scores if s.scenario == "budget-hard-breach-halts-new-work")
    assert halted.binaries == ()


def test_the_suite_covers_every_path_guard_and_terminal_outcome(scenarios):
    paths = {s.expect.path for s in scenarios}
    outcomes = {s.expect.outcome for s in scenarios}
    guards = {g for s in scenarios for g in s.expect.guards}

    assert {orchestrator.HEAL, orchestrator.IMPLEMENT, orchestrator.IMPROVE} <= paths
    assert {orchestrator.MERGED, orchestrator.RECOVERED, orchestrator.IDLE, bench.HALTED} <= outcomes
    assert guards == {
        orchestrator.GUARD_NEEDS_REFINEMENT,
        orchestrator.GUARD_IDLE_DEDUPE,
        orchestrator.GUARD_WORKFLOW_REVERT,
        orchestrator.GUARD_COMPLETENESS,
        orchestrator.GUARD_REPRO,
        orchestrator.GUARD_REVIEW_BLOCK,
        orchestrator.GUARD_REMOTE_CI,
        bench.GUARD_BUDGET_HARD,
        bench.GUARD_BUDGET_SOFT,
    }
    # At least one scenario must assert that NO guard fires: a suite that only
    # ever expects interventions would not notice a guard firing spuriously.
    assert any(s.expect.guards == () for s in scenarios)


def test_scenarios_are_traceable_to_the_lessons_that_taught_them(scenarios):
    cited = [s for s in scenarios if s.lesson]
    assert len(cited) >= 3
    # load_scenarios(repo_root=...) already refused a dangling citation; assert
    # the notes really are in the vault so the check cannot rot into a no-op.
    for scenario in cited:
        assert (ROOT / "knowledge" / "lessons" / f"{scenario.lesson}.md").is_file()


# --- the scoring is not vacuous ---------------------------------------------


def test_a_wrong_expectation_fails_the_scenario(scenarios):
    scenario = next(s for s in scenarios if s.name == "implement-a-well-formed-ticket-merges-on-green")
    wrong = replace(scenario, expect=replace(scenario.expect, tier="heavy"))

    score = bench.run_scenario(wrong, load_config(CORE))

    assert not score.ok
    assert "tier: expected heavy, got standard" in score.reason()


def test_an_inverted_decide_path_is_caught_and_named(scenarios, monkeypatch):
    monkeypatch.setattr(
        orchestrator, "decide_path", lambda ci_green, has_tickets: orchestrator.IMPROVE
    )
    scenario = next(s for s in scenarios if s.name == "implement-a-well-formed-ticket-merges-on-green")

    score = bench.run_scenario(scenario, load_config(CORE))

    assert not score.ok
    assert "path: expected implement, got improve" in score.reason()


def test_a_scenario_that_explodes_is_a_failure_not_a_crashed_suite(scenarios, monkeypatch):
    def boom(*_a, **_kw):
        raise RuntimeError("orchestrator exploded")

    monkeypatch.setattr(bench, "run_once", boom)
    # Only scenarios that actually reach `run_once` (the budget-halt one never
    # starts an iteration, so nothing would explode there).
    running = [s for s in scenarios if s.expect.outcome != bench.HALTED][:2]
    result = bench.run_suite(running, load_config(CORE))

    assert not result.ok
    assert all("RuntimeError: orchestrator exploded" in s.error for s in result.scores)


# --- the loader refuses malformed scenarios ---------------------------------


def _doc(**overrides) -> dict:
    doc = {**VALID_DOC, "expect": dict(VALID_DOC["expect"])}
    for key, value in overrides.items():
        if value is None:
            doc.pop(key, None)
        else:
            doc[key] = value
    return doc


MALFORMED = {
    "not-a-mapping": ["just", "a", "list"],
    "no-name": _doc(name=None),
    "no-description": _doc(description=None),
    "no-expect": _doc(expect=None),
    "unknown-top-level-key": _doc(scenaro_typo="oops"),
    "unknown-guard": _doc(expect={"path": "heal", "guards": ["teleport"], "outcome": "merged"}),
    "unknown-outcome": _doc(expect={"path": "heal", "guards": [], "outcome": "vanished"}),
    "unknown-path": _doc(expect={"path": "sideways", "guards": [], "outcome": "merged"}),
    "missing-guards": _doc(expect={"path": "heal", "outcome": "merged"}),
    "missing-path": _doc(expect={"guards": [], "outcome": "merged"}),
    "guards-not-a-list": _doc(expect={"path": "heal", "guards": "repro", "outcome": "merged"}),
    "pending-remote-ci": _doc(remote_ci="PENDING"),
    "rule-without-cmd": _doc(transcript=[{"stdout": "hi"}]),
    "rule-with-unknown-key": _doc(transcript=[{"cmd": ["git"], "stdout_text": "hi"}]),
    "rule-with-unknown-ref": _doc(transcript=[{"cmd": ["claude"], "stdout_ref": "oracle"}]),
    "rule-with-two-sources": _doc(
        transcript=[{"cmd": ["claude"], "stdout": "x", "stdout_ref": "agent_ok"}]
    ),
    "role-on-a-non-claude-rule": _doc(transcript=[{"cmd": ["git"], "role": "reviewer"}]),
    "unknown-role": _doc(transcript=[{"cmd": ["claude"], "role": "auditor"}]),
    "empty-responses": _doc(transcript=[{"cmd": ["git"], "responses": []}]),
    "issue-without-a-number": _doc(issues=[{"title": "no number"}]),
    "ledger-with-unknown-key": _doc(ledger=[{"tier": "heavy", "cost": 3}]),
    "ledger-with-unknown-tier": _doc(ledger=[{"tier": "titanic"}]),
}


@pytest.mark.parametrize("case", sorted(MALFORMED))
def test_the_loader_refuses_a_malformed_scenario(case):
    with pytest.raises(bench.ScenarioError):
        bench.parse_scenario(MALFORMED[case], source=f"{case}.yaml")


def test_a_valid_document_still_parses():
    scenario = bench.parse_scenario(_doc(), source="sample.yaml")
    assert scenario.name == "sample"
    assert scenario.expect.outcome == orchestrator.MERGED
    assert scenario.remote_ci == "SUCCESS"


def test_a_scenario_file_must_be_named_after_its_scenario(tmp_path):
    path = tmp_path / "different-name.yaml"
    path.write_text(yaml.safe_dump(_doc()), encoding="utf-8")
    with pytest.raises(bench.ScenarioError, match="must match"):
        bench.load_scenario(path)


def test_one_malformed_file_fails_the_whole_directory_load(tmp_path):
    (tmp_path / "sample.yaml").write_text(yaml.safe_dump(_doc()), encoding="utf-8")
    (tmp_path / "broken.yaml").write_text("name: broken\n", encoding="utf-8")
    # Refused outright: a suite that silently skipped it would report a green
    # board for scenarios it never ran.
    with pytest.raises(bench.ScenarioError):
        bench.load_scenarios(tmp_path)


def test_an_empty_scenario_directory_is_an_error(tmp_path):
    with pytest.raises(bench.ScenarioError, match="no scenarios"):
        bench.load_scenarios(tmp_path)


def test_a_dangling_lesson_citation_is_refused(tmp_path):
    doc = _doc(lesson="2099-01-01-a-note-that-was-never-written")
    (tmp_path / "sample.yaml").write_text(yaml.safe_dump(doc), encoding="utf-8")
    with pytest.raises(bench.ScenarioError, match="does not exist"):
        bench.load_scenarios(tmp_path, repo_root=ROOT)


def test_a_missing_baseline_is_an_error(tmp_path):
    with pytest.raises(bench.ScenarioError, match="no bench baseline"):
        bench.load_baseline(tmp_path / "baseline.json")


# --- the transcript runner --------------------------------------------------


def test_the_transcript_refuses_a_command_it_has_no_rule_for():
    scenario = bench.parse_scenario(_doc(), source="sample.yaml")
    runner = bench.TranscriptRunner(scenario, repo_root="/tmp/bench")
    with pytest.raises(bench.TranscriptError, match="no transcript rule"):
        runner(["curl", "https://example.com"])


def test_responses_are_consumed_in_order_then_the_last_one_repeats():
    doc = _doc(
        transcript=[{"cmd": ["ruff", "check"], "responses": [{"code": 1}, {"code": 0}]}]
    )
    scenario = bench.parse_scenario(doc, source="sample.yaml")
    runner = bench.TranscriptRunner(scenario, repo_root="/tmp/bench")

    codes = [runner(["ruff", "check", "."]).code for _ in range(3)]
    assert codes == [1, 0, 0]


def test_the_worker_and_the_reviewer_get_different_canned_replies():
    scenario = bench.parse_scenario(_doc(), source="sample.yaml")
    runner = bench.TranscriptRunner(scenario, repo_root="/tmp/bench")

    worker = runner(["claude", "-p", "implement the ticket"]).stdout
    reviewer = runner(["claude", "-p", f"{review.PROMPT_MARKER} judge it"]).stdout

    assert worker == bench.AGENT_OK
    assert reviewer == bench.REVIEW_APPROVE


# --- the CLI ----------------------------------------------------------------


def test_bench_cli_runs_one_scenario_and_leaves_the_board_alone(capsys):
    rc = main([
        "bench", "--root", str(ROOT), "--scenario", "improve-files-its-own-ticket-and-merges",
    ])
    out = capsys.readouterr().out
    assert rc == 0
    assert "improve-files-its-own-ticket-and-merges" in out
    assert "aggregate: 1/1 (1.00)" in out
    assert "scoreboard: not written (partial run)" in out


def test_bench_cli_json_output_is_machine_readable(capsys):
    rc = main([
        "bench", "--json", "--root", str(ROOT),
        "--scenario", "budget-hard-breach-halts-new-work",
    ])
    payload = json.loads(capsys.readouterr().out)
    assert rc == 0
    assert payload["aggregate"] == 1.0
    entry = payload["scenarios"][0]
    assert entry["name"] == "budget-hard-breach-halts-new-work"
    assert entry["binaries"] == []          # halted before spawning anything
    assert {"path", "guards", "outcome"} <= {c["name"] for c in entry["checks"]}
    assert payload["regressions"] == []


def test_bench_cli_exits_non_zero_and_names_the_regressed_scenario(capsys, monkeypatch):
    monkeypatch.setattr(
        orchestrator, "decide_path", lambda ci_green, has_tickets: orchestrator.HEAL
    )
    rc = main(["bench", "--root", str(ROOT), "--no-write"])
    out = capsys.readouterr().out

    assert rc == 1
    assert "FAIL implement-a-well-formed-ticket-merges-on-green" in out
    assert "REGRESSION: aggregate score" in out
    # --no-write: the committed board is never rewritten by a failing run.
    assert "scoreboard:" not in out


def test_bench_cli_reports_a_malformed_suite_instead_of_scoring_it(tmp_path, capsys):
    (tmp_path / "broken.yaml").write_text("name: broken\n", encoding="utf-8")
    rc = main(["bench", "--root", str(ROOT), "--scenarios", str(tmp_path)])
    err = capsys.readouterr().err
    assert rc == 2
    assert "bench:" in err


def test_bench_cli_rejects_an_unknown_scenario_name(capsys):
    rc = main(["bench", "--root", str(ROOT), "--scenario", "no-such-scenario"])
    assert rc == 2
    assert "no scenario named" in capsys.readouterr().err
