"""The architect's control surface.

- ``DIRECTION.md``: single-entrance steering doc - Now / Issues Map / Direction.
  Regenerated on every brief; the "Architect Notes" section between its markers
  is preserved verbatim (it belongs to the human).
- Review brief: end-of-block summary posted as a GitHub issue (label ``review``)
  linking every PR / ticket / lesson / whitepaper, ready for the /review-next
  session where feedback becomes ADRs and tickets.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

from . import github
from .config import CoreConfig
from .knowledge import KnowledgeBase
from .ledger import BlockAggregate
from .proc import Runner, run

NOTES_START = "<!-- architect-notes:start -->"
NOTES_END = "<!-- architect-notes:end -->"
_NOTES_RE = re.compile(re.escape(NOTES_START) + r"(.*?)" + re.escape(NOTES_END), re.DOTALL)

_DEFAULT_NOTES = """
_Write here. This section is never overwritten by automation._
"""


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


@dataclass
class BlockReport:
    """What one half-day block actually did (input to brief + review issue)."""

    cycle_index: int
    synthesized: list[int] = field(default_factory=list)  # ticket numbers filed
    # Whether synthesis is still finding new ground: how many candidates the
    # heavy model produced, and which ones repo memory already covered.
    synthesis_candidates: int = 0
    synthesis_flagged: list[int] = field(default_factory=list)  # filed as possible-duplicate
    synthesis_skipped: list[str] = field(default_factory=list)  # "title - 0.81 match with #12"
    iterations: list[str] = field(default_factory=list)   # IterationResult.describe() lines
    merged_prs: list[int] = field(default_factory=list)
    recovered_prs: list[int] = field(default_factory=list)
    whitepaper: str = ""                                   # note name
    articles: list[str] = field(default_factory=list)      # file paths
    cost: BlockAggregate | None = None                     # quota-ledger aggregate
    notes: list[str] = field(default_factory=list)


def preserved_notes(direction_path: Path) -> str:
    """Extract the human-owned Architect Notes from an existing DIRECTION.md."""
    if not direction_path.exists():
        return _DEFAULT_NOTES
    m = _NOTES_RE.search(direction_path.read_text())
    return m.group(1) if m else _DEFAULT_NOTES


def _issues_map(cfg: CoreConfig, *, runner: Runner = run) -> str:
    """Open tickets grouped by priority, one level of grouping, one of detail."""
    issues = github.list_open_issues(cfg.repo_slug, runner=runner)
    if not issues:
        return "_Backlog is empty - the next cycle will synthesize new work._"
    groups: dict[str, list[github.Issue]] = {}
    for i in issues:
        prio = next((lb for lb in i.labels if lb.startswith("priority:")), "priority:-")
        groups.setdefault(prio, []).append(i)
    lines: list[str] = []
    for prio in sorted(groups):
        lines.append(f"- **{prio.split(':', 1)[1]}**")
        for i in groups[prio]:
            flags = []
            if i.is_blocked:
                flags.append("BLOCKED")
            if i.assignees:
                flags.append("claimed")
            suffix = f" _({', '.join(flags)})_" if flags else ""
            lines.append(f"  - #{i.number} {i.title}{suffix}")
    return "\n".join(lines)


def render_direction(
    cfg: CoreConfig,
    *,
    repo_root: Path,
    runner: Runner = run,
) -> str:
    """Render DIRECTION.md: Now / Issues Map / Direction (+ preserved notes)."""
    kb = KnowledgeBase.from_config(cfg, repo_root)
    lessons = kb.lesson_notes()
    papers = kb.whitepaper_notes()
    goals = "\n".join(
        f"- **{g.get('id')}** - {g.get('title')}: {str(g.get('description', '')).strip()}"
        for g in cfg.goals
    )
    notes = preserved_notes(repo_root / cfg.governance.get("direction_doc", "governance/DIRECTION.md"))
    return f"""# Direction - {cfg.name}

> Single-entrance steering doc. Regenerated by `hsai brief` at the end of every
> block; the **Architect Notes** section is yours and is preserved verbatim.
> Updated: {_now()}

## Now (current state)
- Loop: two-phase engine (heavy-model synthesis -> structured tickets -> cheaper
  implementation agents), sequential blocks of {cfg.cycle.get('block_size', 5)},
  {cfg.governance.get('reviews_per_day', 2)} reviews/day.
- Knowledge: {len(lessons)} lessons, {len(papers)} whitepapers ([[Knowledge Base MOC]]).
- Invariants: ticket-linked PRs, model recorded, lesson per PR, green-gated
  merges (remote CI is truth), subscription-only models, SDLC evidence per PR.

## Issues Map
{_issues_map(cfg, runner=runner)}

## Direction (where we are going)
{goals}

Review rhythm: scheduled cycle -> whitepaper + brief -> architect runs
`/review-next` -> feedback becomes ADRs + tickets -> PR merged -> next block.

## Architect Notes
{NOTES_START}{notes}{NOTES_END}
"""


def write_direction(cfg: CoreConfig, *, repo_root: str | Path, runner: Runner = run) -> Path:
    root = Path(repo_root)
    path = root / cfg.governance.get("direction_doc", "governance/DIRECTION.md")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_direction(cfg, repo_root=root, runner=runner))
    return path


def _cost_summary(cost: BlockAggregate | None) -> str:
    """Block economics for the review brief (empty ledger -> note).

    Tokens-per-merged-PR is called out on its own line: it is the number the
    architect steers on (quota spent per unit of delivered work), so it should
    not be buried at the end of the summary string.
    """
    if cost is None or cost.iterations == 0:
        return "_no ledger records for this block_"
    per_pr = cost.tokens_per_merged_pr()
    efficiency = (
        f"{per_pr:.0f} tokens per merged PR "
        f"({cost.total_tokens} tokens / {cost.merged_iterations} merged)"
        if per_pr
        else "tokens per merged PR: _not available_ "
        "(nothing merged, or the CLI reported no token counts)"
    )
    return f"{cost.summary()}\n\n**Efficiency:** {efficiency}"


def _synthesis_novelty(report: BlockReport) -> str:
    """Is synthesis still finding new ground, or restating what already shipped?

    A block where most candidates were withheld as duplicates is the signal that
    the planner has exhausted its current context - the architect should widen
    the reference rotation or re-aim the goals rather than keep paying for the
    heavy tier.
    """
    if not report.synthesis_candidates and not report.synthesis_skipped:
        return "**Synthesis novelty:** _synthesis did not run this block._"
    filed = len(report.synthesized)
    skipped = report.synthesis_skipped
    lines = [
        f"**Synthesis novelty:** {report.synthesis_candidates} candidate(s) parsed - "
        f"{filed} filed, {len(skipped)} skipped as near-duplicates of known tickets."
    ]
    lines += [f"- skipped: {s}" for s in skipped]
    return "\n".join(lines)


def render_brief(cfg: CoreConfig, report: BlockReport) -> str:
    """The review-issue body for one block: everything clickable in one place."""
    repo = cfg.repo_slug
    synth = (
        "\n".join(
            f"- #{n} (synthesized this block)"
            + (" **possible-duplicate**" if n in report.synthesis_flagged else "")
            for n in report.synthesized
        )
        or "_none - backlog was sufficient_"
    )
    iters = "\n".join(f"- `{line}`" for line in report.iterations) or "_none_"
    merged = "\n".join(
        f"- https://github.com/{repo}/pull/{n}" for n in report.merged_prs
    ) or "_none_"
    recovered = "\n".join(
        f"- https://github.com/{repo}/pull/{n} (closed by retry policy)"
        for n in report.recovered_prs
    ) or "_none_"
    paper = f"`knowledge/whitepapers/{report.whitepaper}.md`" if report.whitepaper else "_none_"
    articles = "\n".join(f"- `{a}`" for a in report.articles) or "_none_"
    cost = _cost_summary(report.cost)
    novelty = _synthesis_novelty(report)
    extra = "\n".join(f"- {n}" for n in report.notes)
    return f"""# Block review - cycle {report.cycle_index}

One block of the twice-daily governance rhythm. Review here, then run
`/review-next` in a Claude Code session: it walks un-reviewed lessons
sequentially, records your feedback as ADRs, and ends with a merged PR.

## Tickets synthesized (heavy model)
{synth}

{novelty}

## Iterations
{iters}

## PRs merged
{merged}

## PRs recovered (failed the gate)
{recovered}

## Cost this block (quota ledger)
{cost}

## Knowledge produced
- Whitepaper: {paper}
- Persona articles:
{articles}

## Steering doc
`governance/DIRECTION.md` was refreshed - review the **Now / Issues Map /
Direction** layers and leave comments below or in your Architect Notes section.

{("## Notes" + chr(10) + extra) if extra else ""}
"""


def open_review_issue(
    cfg: CoreConfig, report: BlockReport, *, runner: Runner = run
) -> int:
    label = cfg.governance.get("review_label", "review")
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M")
    return github.create_issue(
        cfg.repo_slug,
        f"review: block {report.cycle_index} - {stamp} UTC",
        render_brief(cfg, report),
        [label],
        runner=runner,
    )
