"""The reference-set observatory: cached, diffed study digests per project.

Until this module existed, :func:`hsai.synthesis.build_context_pack` re-fetched
each reference project's README, last commit subjects and workflow inventory on
every cycle, handed them to the heavy model, and threw them away. Nothing
persisted, so the planner could not tell what had CHANGED in a project since it
was last studied, could not see what this repo had already taken from it, and
re-derived the same observations every rotation - the recurring "refresh
reference-set snapshot and extract one practice" chore is the visible symptom.
G1 says every improvement traces back to a field observation; without a durable
record of the observation, the trace stopped at the ticket.

Four pieces, all dependency-free and all pure once the network call is done:

1. **A digest cache.** :func:`observe` writes one JSON file per project at
   ``knowledge/reference/<owner>__<repo>.json`` - when it was fetched, the
   default branch and its head sha, the README's hash and first N bytes, the
   commit-subject window, and the workflow inventory. Every stored text is
   capped so the vault cannot bloat.
2. **A delta.** :func:`diff_digest` answers "what is new since the last time we
   looked": commit subjects newer than the stored head, workflow files added or
   removed, and whether the README hash moved. On a first-ever observation
   there is no "since last cycle", so the delta is marked ``baseline`` and
   reports nothing as new rather than dumping the whole window as change.
3. **An adoption index.** :func:`build_adoption_index` scans the lessons this
   repo has written (their ``## References (reference-set evidence)`` section)
   plus the :mod:`hsai.practices` registry, producing repo -> what we have
   already taken from it. Rendered into the synthesis prompt as ground the
   planner must not re-propose.
4. **A dossier per project.** :func:`write_dossiers` renders an Obsidian note
   per reference project (what it is, what we adopted, what changed, open
   questions) plus a "Reference Set MOC" indexing all of them. Regenerated by
   :meth:`hsai.knowledge.KnowledgeBase.reindex_mocs` - the same
   serialized-derived-file rule the other MOCs follow, so parallel PRs never
   collide on them.

Staleness is an explicit, surfaced state (:func:`stale_report`): DIRECTION.md's
"Now" section reports how many projects have not been observed inside the
configured window, and ``hsai observe`` is the way to fix it without burning a
cycle.
"""
from __future__ import annotations

import hashlib
import json
import re
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, replace
from datetime import datetime, timezone
from pathlib import Path

from .config import CoreConfig, ReferenceRepo
from .knowledge import LessonRecord, slugify
from .practices import Practice
from .proc import Runner, run

SCHEMA_VERSION = 1

# Where the cache and the dossiers live. Mirrored as the `reference_dir`
# default in hsai.knowledge.KnowledgeBase (a literal there, to keep this
# module - which reads notes through hsai.knowledge - out of an import cycle).
REFERENCE_DIR_DEFAULT = "knowledge/reference"
REFERENCE_MOC_NAME = "Reference Set MOC"

DEFAULT_COMMITS = 30
DEFAULT_README_BYTES = 4000
DEFAULT_STALE_AFTER_DAYS = 7

# Hard caps on what one cache entry may store, so ten dossiers plus ten cache
# files stay a few hundred kilobytes rather than a mirror of ten repositories.
MAX_SUBJECT_CHARS = 200
MAX_WORKFLOWS = 60
# Rendering caps - the delta is the part the planner must actually read.
MAX_DELTA_COMMITS_SHOWN = 20
MAX_ADOPTED_SHOWN = 12

# Headings the synthesis prompt renders per repo, in this order: what changed
# first, then the full digest, then what we already took from the project.
DELTA_HEADING = "Changed since the last cycle"
BASELINE_HEADING = "Baseline digest"
ADOPTED_FROM_HEADING = "Practices already adopted from this project (do NOT re-propose)"

# `gh api` prints one line per commit: sha, a tab, then the subject line.
_COMMIT_JQ = '.[] | .sha + "\\t" + (.commit.message | split("\\n")[0])'

_ISO_Z_RE = re.compile(r"Z$")


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _now_iso() -> str:
    return _now().isoformat(timespec="seconds")


def _today() -> str:
    return _now().strftime("%Y-%m-%d")


def _parse_iso(text: str) -> datetime | None:
    """Parse an ISO-8601 stamp, tolerating a trailing ``Z`` (3.10 cannot)."""
    if not text:
        return None
    try:
        stamp = datetime.fromisoformat(_ISO_Z_RE.sub("+00:00", text.strip()))
    except ValueError:
        return None
    return stamp if stamp.tzinfo else stamp.replace(tzinfo=timezone.utc)


@dataclass(frozen=True)
class ObservatoryConfig:
    """The ``observatory`` block of core.yaml, with documented defaults."""

    dir: str = REFERENCE_DIR_DEFAULT
    commits: int = DEFAULT_COMMITS
    readme_bytes: int = DEFAULT_README_BYTES
    stale_after_days: int = DEFAULT_STALE_AFTER_DAYS

    @classmethod
    def from_core(cls, cfg: CoreConfig | None) -> ObservatoryConfig:
        raw = (cfg.observatory if cfg else None) or {}
        d = cls()
        return cls(
            dir=str(raw.get("dir", d.dir)),
            commits=int(raw.get("commits", d.commits)),
            readme_bytes=int(raw.get("readme_bytes", d.readme_bytes)),
            stale_after_days=int(raw.get("stale_after_days", d.stale_after_days)),
        )


@dataclass(frozen=True)
class Commit:
    """One commit in the fetched window: its sha and its subject line."""

    sha: str
    subject: str


@dataclass(frozen=True)
class DigestDelta:
    """What changed in one project since the last stored observation.

    ``baseline`` marks a first-ever observation: there is no previous head to
    diff against, so nothing is reported as "new since last cycle" - the whole
    digest IS the starting point. ``fetch_failed`` marks the opposite edge: the
    fetch came back empty (no ``gh``, rate limit, repo moved), so the cache was
    deliberately left untouched and the last good observation still stands.
    """

    repo: str
    baseline: bool = False
    new_commits: tuple[str, ...] = ()  # subjects, newest first
    added_workflows: tuple[str, ...] = ()
    removed_workflows: tuple[str, ...] = ()
    readme_changed: bool = False
    previous_head: str = ""
    previous_fetched_at: str = ""
    # The previous head fell outside the fetched commit window: everything in
    # `new_commits` is genuinely new, but there may be more we cannot see.
    window_incomplete: bool = False
    fetch_failed: bool = False

    @property
    def changed(self) -> bool:
        return bool(
            self.new_commits
            or self.added_workflows
            or self.removed_workflows
            or self.readme_changed
        )

    def summary(self) -> str:
        """One line, for the CLI and the dossier table."""
        if self.fetch_failed:
            return "fetch returned nothing - kept the cached observation"
        if self.baseline:
            return "baseline (first observation)"
        if not self.changed:
            return "no change"
        bits: list[str] = []
        if self.new_commits:
            bits.append(f"{len(self.new_commits)} new commit(s)")
        if self.added_workflows:
            bits.append(f"+{len(self.added_workflows)} workflow(s)")
        if self.removed_workflows:
            bits.append(f"-{len(self.removed_workflows)} workflow(s)")
        if self.readme_changed:
            bits.append("README changed")
        return ", ".join(bits)

    def render(self) -> str:
        """The block the planner reads first, before the baseline digest."""
        since = f" ({self.previous_fetched_at})" if self.previous_fetched_at else ""
        if self.fetch_failed:
            return (
                "_The fetch returned nothing this cycle (`gh` unavailable, rate-limited, or "
                f"the repo moved) - what follows is the last good observation{since}._"
            )
        if self.baseline:
            return (
                "_BASELINE - first recorded observation of this project. Nothing here is new "
                "*since the last cycle*; read the digest below as the starting point._"
            )
        head = self.previous_head[:7] or "?"
        lines = [f"Since the previous observation{since} at head `{head}`:"]
        if self.new_commits:
            shown = self.new_commits[:MAX_DELTA_COMMITS_SHOWN]
            lines.append(f"- New commits ({len(self.new_commits)}):")
            lines.extend(f"  - {s}" for s in shown)
            hidden = len(self.new_commits) - len(shown)
            if hidden > 0:
                lines.append(f"  - _(+{hidden} more not shown)_")
            if self.window_incomplete:
                lines.append(
                    "  - _(the previous head is outside the fetched window - there may be more)_"
                )
        else:
            lines.append("- New commits: none")
        lines.append(f"- Workflows added: {', '.join(self.added_workflows) or 'none'}")
        lines.append(f"- Workflows removed: {', '.join(self.removed_workflows) or 'none'}")
        lines.append(f"- README: {'CHANGED' if self.readme_changed else 'unchanged'}")
        return "\n".join(lines)

    def to_dict(self) -> dict:
        return {
            "baseline": self.baseline,
            "new_commits": list(self.new_commits),
            "added_workflows": list(self.added_workflows),
            "removed_workflows": list(self.removed_workflows),
            "readme_changed": self.readme_changed,
            "previous_head": self.previous_head,
            "previous_fetched_at": self.previous_fetched_at,
            "window_incomplete": self.window_incomplete,
            "fetch_failed": self.fetch_failed,
        }

    @classmethod
    def from_dict(cls, repo: str, data: Mapping) -> DigestDelta:
        return cls(
            repo=repo,
            baseline=bool(data.get("baseline", False)),
            new_commits=tuple(str(s) for s in data.get("new_commits") or ()),
            added_workflows=tuple(str(s) for s in data.get("added_workflows") or ()),
            removed_workflows=tuple(str(s) for s in data.get("removed_workflows") or ()),
            readme_changed=bool(data.get("readme_changed", False)),
            previous_head=str(data.get("previous_head", "")),
            previous_fetched_at=str(data.get("previous_fetched_at", "")),
            window_incomplete=bool(data.get("window_incomplete", False)),
            fetch_failed=bool(data.get("fetch_failed", False)),
        )


@dataclass(frozen=True)
class Digest:
    """One cached observation of a reference project.

    ``delta`` is the diff recorded WHEN this digest was fetched, stored
    alongside it so the dossier writer (which never touches the network) can
    still say what changed last cycle.
    """

    repo: str
    fetched_at: str = ""
    default_branch: str = ""
    head_sha: str = ""
    readme_hash: str = ""
    readme_excerpt: str = ""
    commits: tuple[Commit, ...] = ()
    workflows: tuple[str, ...] = ()
    delta: DigestDelta | None = None

    def is_empty(self) -> bool:
        """Nothing at all came back - never cache this over a good observation."""
        return not (self.head_sha or self.readme_hash or self.commits or self.workflows)

    def render(self) -> str:
        head = f"`{self.default_branch or '?'}` @ `{(self.head_sha or '?')[:7]}`"
        parts = [f"Observed {self.fetched_at or '(never)'} - default branch {head}"]
        if self.readme_excerpt:
            parts.append("README (truncated):\n" + self.readme_excerpt)
        if self.commits:
            subjects = "\n".join(f"- {c.subject}" for c in self.commits)
            parts.append("Recent commit subjects:\n" + subjects)
        if self.workflows:
            parts.append("CI workflows:\n" + ", ".join(self.workflows))
        if len(parts) == 1:
            parts.append("(no data fetched - `gh` unavailable, rate-limited, or the repo moved)")
        return "\n\n".join(parts)

    def to_dict(self) -> dict:
        payload: dict = {
            "schema_version": SCHEMA_VERSION,
            "repo": self.repo,
            "fetched_at": self.fetched_at,
            "default_branch": self.default_branch,
            "head_sha": self.head_sha,
            "readme_hash": self.readme_hash,
            "readme_excerpt": self.readme_excerpt,
            "commits": [{"sha": c.sha, "subject": c.subject} for c in self.commits],
            "workflows": list(self.workflows),
        }
        if self.delta is not None:
            payload["last_delta"] = self.delta.to_dict()
        return payload

    @classmethod
    def from_dict(cls, data: Mapping) -> Digest:
        repo = str(data.get("repo", ""))
        raw_delta = data.get("last_delta")
        return cls(
            repo=repo,
            fetched_at=str(data.get("fetched_at", "")),
            default_branch=str(data.get("default_branch", "")),
            head_sha=str(data.get("head_sha", "")),
            readme_hash=str(data.get("readme_hash", "")),
            readme_excerpt=str(data.get("readme_excerpt", "")),
            commits=tuple(
                Commit(sha=str(c.get("sha", "")), subject=str(c.get("subject", "")))
                for c in data.get("commits") or ()
            ),
            workflows=tuple(str(w) for w in data.get("workflows") or ()),
            delta=DigestDelta.from_dict(repo, raw_delta) if isinstance(raw_delta, Mapping) else None,
        )


# --- cache IO -----------------------------------------------------------------

def reference_dir(root: str | Path, cfg: CoreConfig | None = None) -> Path:
    """The directory holding the digest cache and the dossiers (not created)."""
    return Path(root) / ObservatoryConfig.from_core(cfg).dir


def cache_name(repo: str) -> str:
    """``owner/repo`` -> ``owner__repo``: one flat, collision-free filename."""
    return repo.strip().replace("/", "__")


def digest_path(directory: str | Path, repo: str) -> Path:
    return Path(directory) / f"{cache_name(repo)}.json"


def read_digest(directory: str | Path, repo: str) -> Digest | None:
    """The last stored observation, or ``None`` when there is none we can read.

    A missing, unreadable or corrupt cache entry is not an error: it means "we
    have never observed this", which :func:`diff_digest` renders as a baseline.
    """
    path = digest_path(directory, repo)
    try:
        data = json.loads(path.read_text())
    except (OSError, ValueError):
        return None
    if not isinstance(data, Mapping):
        return None
    digest = Digest.from_dict(data)
    return digest if digest.repo else replace(digest, repo=repo)


def write_digest(directory: str | Path, digest: Digest) -> Path:
    path = digest_path(directory, digest.repo)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(digest.to_dict(), indent=2, ensure_ascii=False) + "\n")
    return path


# --- fetching + diffing -------------------------------------------------------

def _parse_commits(stdout: str, limit: int) -> tuple[Commit, ...]:
    commits: list[Commit] = []
    for line in stdout.splitlines():
        if not line.strip():
            continue
        sha, _, subject = line.partition("\t")
        if not subject:
            sha, subject = "", sha
        commits.append(Commit(sha=sha.strip(), subject=subject.strip()[:MAX_SUBJECT_CHARS]))
        if len(commits) >= limit:
            break
    return tuple(commits)


def fetch_digest(
    repo: str,
    *,
    runner: Runner = run,
    commits: int = DEFAULT_COMMITS,
    readme_bytes: int = DEFAULT_README_BYTES,
) -> Digest:
    """Fetch one project's study material through ``gh``. Never raises.

    Each of the four calls degrades independently: a project with no README, no
    workflows directory, or a rate-limited commit listing still yields whatever
    the other calls returned.
    """
    branch = ""
    meta = runner(["gh", "api", f"repos/{repo}", "--jq", ".default_branch"])
    if meta.ok:
        branch = meta.stdout.strip()

    readme_hash = readme_excerpt = ""
    readme = runner(
        ["gh", "api", f"repos/{repo}/readme", "-H", "Accept: application/vnd.github.raw"]
    )
    if readme.ok and readme.stdout.strip():
        readme_hash = hashlib.sha256(readme.stdout.encode("utf-8", "replace")).hexdigest()
        readme_excerpt = readme.stdout[:readme_bytes]

    log = runner(["gh", "api", f"repos/{repo}/commits?per_page={commits}", "--jq", _COMMIT_JQ])
    parsed = _parse_commits(log.stdout, commits) if log.ok else ()

    workflows: tuple[str, ...] = ()
    wf = runner(["gh", "api", f"repos/{repo}/contents/.github/workflows", "--jq", ".[].name"])
    if wf.ok and wf.stdout.strip():
        names = sorted(n.strip() for n in wf.stdout.splitlines() if n.strip())
        workflows = tuple(names[:MAX_WORKFLOWS])

    return Digest(
        repo=repo,
        fetched_at=_now_iso(),
        default_branch=branch,
        head_sha=parsed[0].sha if parsed else "",
        readme_hash=readme_hash,
        readme_excerpt=readme_excerpt,
        commits=parsed,
        workflows=workflows,
    )


def diff_digest(old: Digest | None, new: Digest) -> DigestDelta:
    """What is new in ``new`` relative to ``old``.

    A first-ever observation (``old is None``) yields a delta marked
    ``baseline`` with EMPTY change lists: "new since the last cycle" is
    undefined when there was no last cycle, and reporting the whole commit
    window as change would teach the planner exactly the wrong thing.
    """
    if old is None:
        return DigestDelta(repo=new.repo, baseline=True)

    new_subjects: list[str] = []
    incomplete = False
    if old.head_sha and old.head_sha != new.head_sha:
        found = False
        for commit in new.commits:
            if commit.sha and commit.sha == old.head_sha:
                found = True
                break
            new_subjects.append(commit.subject)
        incomplete = not found

    old_workflows, new_workflows = set(old.workflows), set(new.workflows)
    return DigestDelta(
        repo=new.repo,
        new_commits=tuple(new_subjects),
        added_workflows=tuple(sorted(new_workflows - old_workflows)),
        removed_workflows=tuple(sorted(old_workflows - new_workflows)),
        readme_changed=bool(
            old.readme_hash and new.readme_hash and old.readme_hash != new.readme_hash
        ),
        previous_head=old.head_sha,
        previous_fetched_at=old.fetched_at,
        window_incomplete=incomplete,
    )


def observe(
    directory: str | Path,
    repo: str,
    *,
    runner: Runner = run,
    commits: int = DEFAULT_COMMITS,
    readme_bytes: int = DEFAULT_README_BYTES,
) -> Digest:
    """Fetch, diff against the cache, persist, and return the new digest.

    An empty fetch never overwrites a good observation: the cache is left
    exactly as it was and the returned digest carries a ``fetch_failed`` delta,
    so a missing ``gh`` degrades to "we still know what we knew last cycle"
    instead of erasing the record.
    """
    old = read_digest(directory, repo)
    fresh = fetch_digest(repo, runner=runner, commits=commits, readme_bytes=readme_bytes)
    if fresh.is_empty():
        failed = DigestDelta(
            repo=repo,
            baseline=old is None,
            fetch_failed=True,
            previous_head=old.head_sha if old else "",
            previous_fetched_at=old.fetched_at if old else "",
        )
        # No cache either: report "never observed" rather than stamping a
        # fetch that brought nothing back as though it were an observation.
        return replace(old, delta=failed) if old else Digest(repo=repo, delta=failed)
    stored = replace(fresh, delta=diff_digest(old, fresh))
    write_digest(directory, stored)
    return stored


def observe_all(
    directory: str | Path,
    repos: Sequence[str],
    *,
    runner: Runner = run,
    refresh: bool = False,
    stale_after_days: int = DEFAULT_STALE_AFTER_DAYS,
    commits: int = DEFAULT_COMMITS,
    readme_bytes: int = DEFAULT_README_BYTES,
    now: datetime | None = None,
) -> list[Digest]:
    """Observe every repo whose cache entry is missing or stale.

    ``refresh=True`` re-fetches all of them regardless - the explicit "I want
    fresh data now" switch behind ``hsai observe --refresh``.
    """
    digests: list[Digest] = []
    for repo in repos:
        cached = read_digest(directory, repo)
        if cached is not None and not refresh and not is_stale(cached, stale_after_days, now=now):
            digests.append(cached)
            continue
        digests.append(
            observe(
                directory, repo, runner=runner, commits=commits, readme_bytes=readme_bytes
            )
        )
    return digests


# --- staleness ----------------------------------------------------------------

def age_days(digest: Digest | None, *, now: datetime | None = None) -> float | None:
    """Days since this project was observed - ``None`` when never, or undated."""
    stamp = _parse_iso(digest.fetched_at) if digest else None
    if stamp is None:
        return None
    return max(0.0, ((now or _now()) - stamp).total_seconds() / 86400.0)


def is_stale(
    digest: Digest | None,
    stale_after_days: int = DEFAULT_STALE_AFTER_DAYS,
    *,
    now: datetime | None = None,
) -> bool:
    """Never observed counts as stale - that is the state worth surfacing."""
    age = age_days(digest, now=now)
    return True if age is None else age > stale_after_days


@dataclass(frozen=True)
class StaleReport:
    """How much of the reference set has gone unobserved for too long."""

    total: int
    stale: tuple[str, ...]
    stale_after_days: int

    def line(self) -> str:
        if not self.total:
            return "no reference projects configured"
        if not self.stale:
            return (
                f"all {self.total} reference project(s) observed within the last "
                f"{self.stale_after_days}d"
            )
        shown = ", ".join(self.stale[:3])
        more = ", ..." if len(self.stale) > 3 else ""
        return (
            f"{len(self.stale)} of {self.total} reference project(s) not observed in over "
            f"{self.stale_after_days}d ({shown}{more}) - run `hsai observe --refresh`"
        )


def stale_report(
    directory: str | Path,
    repos: Sequence[str],
    *,
    stale_after_days: int = DEFAULT_STALE_AFTER_DAYS,
    now: datetime | None = None,
) -> StaleReport:
    stale = tuple(
        repo
        for repo in repos
        if is_stale(read_digest(directory, repo), stale_after_days, now=now)
    )
    return StaleReport(total=len(repos), stale=stale, stale_after_days=stale_after_days)


# --- the adoption index -------------------------------------------------------

@dataclass(frozen=True)
class Adoption:
    """One thing this repo has already taken from a reference project."""

    repo: str
    note_name: str
    title: str
    source: str = "lesson"  # lesson | practice


def build_adoption_index(
    lessons: Sequence[LessonRecord] = (),
    practices: Sequence[Practice] = (),
) -> dict[str, tuple[Adoption, ...]]:
    """repo (lowercased slug) -> what this repo has already adopted from it.

    Two sources, both already committed: every lesson's "References
    (reference-set evidence)" section (which is why a lesson names the projects
    that informed it), and the :mod:`hsai.practices` registry, whose entries
    carry an explicit ``source_project``. Pure - the caller supplies the
    records, so this never touches disk.
    """
    grouped: dict[str, list[Adoption]] = {}
    for record in lessons:
        for repo in record.references:
            key = repo.strip().lower()
            if not key:
                continue
            grouped.setdefault(key, []).append(
                Adoption(
                    repo=repo.strip(),
                    note_name=record.note_name,
                    title=record.title,
                    source="lesson",
                )
            )
    for practice in practices:
        key = practice.source_project.strip().lower()
        if not key:
            continue
        grouped.setdefault(key, []).append(
            Adoption(
                repo=practice.source_project.strip(),
                note_name=practice.note_name(),
                title=practice.title,
                source="practice",
            )
        )
    return {
        key: tuple(
            sorted(dict.fromkeys(items), key=lambda a: (a.source, a.note_name, a.title))
        )
        for key, items in grouped.items()
    }


def adoptions_for(
    index: Mapping[str, tuple[Adoption, ...]], repo: str
) -> tuple[Adoption, ...]:
    return index.get(repo.strip().lower(), ())


def render_adopted(index: Mapping[str, tuple[Adoption, ...]], repo: str) -> str:
    """The "do NOT re-propose" block for one project, capped for the prompt."""
    items = adoptions_for(index, repo)
    if not items:
        return f"_(nothing adopted from `{repo}` yet - this project is open ground)_"
    shown = items[:MAX_ADOPTED_SHOWN]
    lines = [f"- **{a.title}** ([[{a.note_name}]], {a.source})" for a in shown]
    hidden = len(items) - len(shown)
    if hidden > 0:
        lines.append(f"- _(+{hidden} more - see [[{dossier_name(repo)}]])_")
    return "\n".join(lines)


def render_section(digest: Digest, index: Mapping[str, tuple[Adoption, ...]]) -> str:
    """One reference project's block in the synthesis context pack.

    Delta first on purpose: the planner should study what is NEW, and only then
    fall back to the standing digest.
    """
    delta = digest.delta or DigestDelta(repo=digest.repo, baseline=True)
    return (
        f"**{DELTA_HEADING}**\n{delta.render()}\n\n"
        f"**{BASELINE_HEADING}**\n{digest.render()}\n\n"
        f"**{ADOPTED_FROM_HEADING}**\n{render_adopted(index, digest.repo)}"
    )


# --- dossiers + the Reference Set MOC ----------------------------------------

def dossier_name(repo: str) -> str:
    """``owner/repo`` -> ``repo``: the note name, and its Obsidian wikilink."""
    return repo.strip().split("/")[-1] or slugify(repo)


def _open_questions(ref: ReferenceRepo, digest: Digest, adopted: Sequence[Adoption]) -> list[str]:
    """Deterministic prompts for the next study pass - derived, never invented."""
    delta = digest.delta
    questions: list[str] = []
    if not adopted:
        questions.append(
            "Nothing has been adopted from this project yet - which of its practices "
            "is worth a ticket?"
        )
    if delta and delta.new_commits:
        questions.append(
            f"What do the {len(delta.new_commits)} new commit(s) since the previous "
            "observation change about our reading of this project?"
        )
    if delta and delta.added_workflows:
        added = ", ".join(f"`{w}`" for w in delta.added_workflows)
        questions.append(f"Do the added workflow(s) ({added}) encode a CI practice we lack?")
    if delta and delta.readme_changed:
        questions.append("The README moved - did the project's stated scope or posture change?")
    if not digest.fetched_at:
        questions.append(
            "This project has never been observed - run `hsai observe --refresh` before "
            "planning against it."
        )
    questions.append(
        f"Which parts of `{ref.repo}` ({ref.note or 'no note recorded'}) have we still "
        "not examined?"
    )
    return questions


def render_dossier(
    ref: ReferenceRepo,
    digest: Digest | None,
    index: Mapping[str, tuple[Adoption, ...]],
    *,
    updated: str = "",
) -> str:
    """One Obsidian note per reference project.

    Stable by construction: everything except the ``updated:`` frontmatter line
    is derived from the cache entry and the committed vault, so regenerating
    without new data produces no diff.
    """
    digest = digest or Digest(repo=ref.repo)
    adopted = adoptions_for(index, ref.repo)
    head = f"`{digest.default_branch or '?'}` @ `{(digest.head_sha or '?')[:7]}`"
    delta = digest.delta or DigestDelta(repo=ref.repo, baseline=True)
    adopted_lines = (
        "\n".join(f"- [[{a.note_name}]] ({a.source}) - {a.title}" for a in adopted)
        or "_Nothing adopted from this project yet._"
    )
    questions = "\n".join(f"- {q}" for q in _open_questions(ref, digest, adopted))
    return f"""---
tags:
  - reference
  - source/{slugify(ref.repo)}
updated: {updated or _today()}
repo: {ref.repo}
---

# {ref.repo}

> Part of [[{REFERENCE_MOC_NAME}]] - [[Knowledge Base MOC]]

| field | value |
| --- | --- |
| repo | `{ref.repo}` |
| rank | {ref.rank or "_(unranked)_"} |
| stars | {ref.stars or "_(unknown)_"} |
| license | {ref.license or "_(unknown)_"} |
| last observed | {digest.fetched_at or "_never_"} |
| default branch | {head} |
| adopted from it | {len(adopted)} |

## What it is
{ref.note or "_(no note recorded in core.yaml)_"}

## What we have adopted
{adopted_lines}

## What changed last cycle
{delta.render()}

## Open questions
{questions}
"""


def render_reference_moc(
    refs: Sequence[ReferenceRepo],
    digests: Mapping[str, Digest],
    index: Mapping[str, tuple[Adoption, ...]],
    *,
    updated: str = "",
    stale_after_days: int = DEFAULT_STALE_AFTER_DAYS,
    now: datetime | None = None,
) -> str:
    """The map of content over every reference-project dossier."""
    rows: list[str] = []
    stale: list[str] = []
    for ref in refs:
        digest = digests.get(ref.repo)
        observed = (digest.fetched_at.split("T")[0] if digest and digest.fetched_at else "_never_")
        if is_stale(digest, stale_after_days, now=now):
            stale.append(ref.repo)
        rows.append(
            f"| `{ref.repo}` | [[{dossier_name(ref.repo)}]] | {observed} | "
            f"{len(adoptions_for(index, ref.repo))} |"
        )
    table = "\n".join(rows) or "| _(no reference projects configured)_ | - | - | - |"
    if refs:
        staleness = (
            f"Stale (not observed in over {stale_after_days}d): **{len(stale)}** of {len(refs)}."
        )
    else:
        staleness = "_No reference projects configured in core.yaml._"
    return f"""---
tags:
  - moc
  - reference
updated: {updated or _today()}
---

# {REFERENCE_MOC_NAME}

Up: [[Knowledge Base MOC]]

The reference projects this loop studies (G1). Each dossier records what the
project is, what we have already adopted from it, and what changed since the
last observation - so a cycle studies what is NEW rather than re-deriving what
is merely present. Total: **{len(refs)}**.

| project | dossier | last observed | adopted |
| --- | --- | --- | --- |
{table}

{staleness} Refresh with `hsai observe --refresh`.
"""


def write_dossiers(
    refs: Sequence[ReferenceRepo],
    *,
    reference_dir: str | Path,
    mocs_dir: str | Path,
    index: Mapping[str, tuple[Adoption, ...]] | None = None,
    stale_after_days: int = DEFAULT_STALE_AFTER_DAYS,
    now: datetime | None = None,
) -> list[Path]:
    """Regenerate every dossier plus the Reference Set MOC from what is cached.

    Purely derived - no network, no model call - which is why it is safe to run
    inside :meth:`hsai.knowledge.KnowledgeBase.reindex_mocs` alongside the other
    serialized index rebuilds.
    """
    index = index if index is not None else {}
    directory = Path(reference_dir)
    directory.mkdir(parents=True, exist_ok=True)
    Path(mocs_dir).mkdir(parents=True, exist_ok=True)
    stamp = _today()

    written: list[Path] = []
    digests: dict[str, Digest] = {}
    for ref in refs:
        digest = read_digest(directory, ref.repo)
        if digest is not None:
            digests[ref.repo] = digest
        path = directory / f"{dossier_name(ref.repo)}.md"
        path.write_text(render_dossier(ref, digest, index, updated=stamp))
        written.append(path)

    moc = Path(mocs_dir) / f"{REFERENCE_MOC_NAME}.md"
    moc.write_text(
        render_reference_moc(
            refs, digests, index,
            updated=stamp, stale_after_days=stale_after_days, now=now,
        )
    )
    written.append(moc)
    return written
