"""Retrieval-grounded planning: the planner reads its own notes before it files.

:mod:`hsai.recall` gave the *workers* a read path into the knowledge base. The
*planner* had none: synthesis built its context pack purely from external
reference projects, so it could re-propose an idea that already failed,
duplicate a shipped capability, or contradict an ADR. This module closes that
gap - the loop stops learning only outward.

Three pieces, all dependency-free and all pure once the notes are parsed:

1. **An index artifact.** :func:`write_index` parses every lesson, whitepaper
   and ADR into a :class:`Note` and serializes it to
   ``knowledge/index/notes.json`` in llama_index's node shape (a stable
   ``id_``, the ``text``, flat ``metadata``) - no embeddings, no vector store.
   Regenerated by ``hsai reindex`` and byte-identical on re-run, so it is a
   reviewable artifact rather than a source of diff noise.
2. **Lexical scoring.** :class:`NoteIndex` ranks notes with BM25 over a
   field-weighted term frequency (title and tags count for more than body
   prose) and a half-life recency decay measured against the newest note in the
   index - never against the wall clock, so two runs over the same corpus rank
   identically and tests can assert exact orderings.
3. **Citation-grade output.** Every hit renders as ``[[note-name]] (outcome) -
   title``: an Obsidian wikilink that resolves in the graph (G3), naming the
   note that justified it (G2). :func:`duplicate_risk` turns the same scoring
   into a verdict - does this candidate restate something we already tried and
   recorded as a failure?

Why a second index next to :mod:`hsai.recall`: recall answers "what should this
worker read for this one task" and weights by outcome and task kind; retrieval
answers "what has this repo already said about this idea", needs a bounded
coverage score a threshold can be set on, and has to persist a citable
artifact. They share the tokenizer and the corpus definition
(:func:`hsai.recall.note_sources`) so they can never drift apart on what the
vault is.
"""
from __future__ import annotations

import json
import math
import re
from collections import Counter
from dataclasses import dataclass
from datetime import date
from pathlib import Path

from .config import CoreConfig
from .knowledge import LessonRecord, parse_note
from .recall import is_indexable, note_sources, tokenize

INDEX_DIR_DEFAULT = "knowledge/index"
INDEX_FILENAME = "notes.json"
SCHEMA_VERSION = 1

# BM25 free parameters - the same defaults hsai.recall uses: term saturation
# (k1) and length normalisation (b).
_K1 = 1.5
_B = 0.75

_NAME_DATE_RE = re.compile(r"^(\d{4}-\d{2}-\d{2})-")
_ISO_DATE_RE = re.compile(r"\d{4}-\d{2}-\d{2}")
_WIKILINK_RE = re.compile(r"^\[\[(.+)\]\]$")

# The heading under which prior art is injected into the synthesis prompt.
PRIOR_ART_HEADING = "Prior art from this repo"
_EMPTY_PRIOR_ART = "_No prior art found - nothing in the knowledge base matches this yet._"


@dataclass(frozen=True)
class RetrievalConfig:
    """The ``knowledge.index`` block of core.yaml, with documented defaults."""

    index_dir: str = INDEX_DIR_DEFAULT
    k: int = 3
    title_boost: float = 3.0
    tag_boost: float = 2.0
    half_life_days: float = 180.0
    duplicate_threshold: float = 0.55
    # Below this many distinct query terms, coverage is noise rather than
    # evidence - a four-word candidate can "cover" a note by accident - so
    # duplicate_risk reports the closest note but never flags it.
    min_query_terms: int = 8

    @classmethod
    def from_core(cls, cfg: CoreConfig | None) -> RetrievalConfig:
        raw = ((cfg.knowledge if cfg else None) or {}).get("index") or {}
        d = cls()
        return cls(
            index_dir=str(raw.get("dir", d.index_dir)),
            k=int(raw.get("k", d.k)),
            title_boost=float(raw.get("title_boost", d.title_boost)),
            tag_boost=float(raw.get("tag_boost", d.tag_boost)),
            half_life_days=float(raw.get("half_life_days", d.half_life_days)),
            duplicate_threshold=float(raw.get("duplicate_threshold", d.duplicate_threshold)),
            min_query_terms=int(raw.get("min_query_terms", d.min_query_terms)),
        )


@dataclass(frozen=True)
class Note:
    """One indexed note: what it is, what it concluded, and its full text."""

    note_name: str
    title: str
    source: str = "lesson"  # lesson | whitepaper | adr
    outcome: str = "unknown"  # pass | fail | unknown
    kind: str = "unknown"
    failure_class: str = ""
    tags: tuple[str, ...] = ()
    created: str = ""  # YYYY-MM-DD, "" when the note carries no date
    body: str = ""

    def to_node(self) -> dict:
        """llama_index's node shape: a stable id, the text, and flat metadata."""
        return {
            "id_": self.note_name,
            "text": self.body,
            "metadata": {
                "note_name": self.note_name,
                "title": self.title,
                "source": self.source,
                "outcome": self.outcome,
                "kind": self.kind,
                "failure_class": self.failure_class,
                "tags": list(self.tags),
                "created": self.created,
            },
        }

    @classmethod
    def from_node(cls, node: dict) -> Note:
        meta = node.get("metadata") or {}
        return cls(
            note_name=str(node.get("id_") or meta.get("note_name", "")),
            title=str(meta.get("title", "")),
            source=str(meta.get("source", "lesson")),
            outcome=str(meta.get("outcome", "unknown")),
            kind=str(meta.get("kind", "unknown")),
            failure_class=str(meta.get("failure_class", "")),
            tags=tuple(str(t) for t in meta.get("tags", ())),
            created=str(meta.get("created", "")),
            body=str(node.get("text", "")),
        )


@dataclass(frozen=True)
class PriorArt:
    """One retrieved note, with the numbers that justified its rank."""

    note_name: str
    title: str = ""
    source: str = "lesson"
    outcome: str = "unknown"
    failure_class: str = ""
    score: float = 0.0
    coverage: float = 0.0  # share of the query's informative vocabulary this note holds

    def label(self) -> str:
        """What the note recorded: its outcome, or its kind when it has none."""
        if self.outcome not in ("pass", "fail"):
            return self.source
        return f"{self.outcome}/{self.failure_class}" if self.failure_class else self.outcome

    def citation(self) -> str:
        """An Obsidian wikilink plus the outcome - the citation form tickets carry."""
        return f"[[{self.note_name}]] ({self.label()}) - {self.title}"


def cite(note: Note) -> str:
    """Citation line for a note we already hold (no scoring involved)."""
    return PriorArt(
        note_name=note.note_name, title=note.title, source=note.source,
        outcome=note.outcome, failure_class=note.failure_class,
    ).citation()


# --- parsing ------------------------------------------------------------------

def _created(record: LessonRecord) -> str:
    """The note's date, from the most trustworthy source available.

    Frontmatter first (every machine-written note has it), then the
    ``YYYY-MM-DD-`` filename prefix, then the first ISO date near the top of the
    body - which is where an ADR states its ``**Date**``.
    """
    if record.created:
        return record.created
    named = _NAME_DATE_RE.match(record.note_name)
    if named:
        return named.group(1)
    found = _ISO_DATE_RE.search(record.body[:400])
    return found.group(0) if found else ""


def _as_date(text: str) -> date | None:
    try:
        return date.fromisoformat(text)
    except ValueError:
        return None


def _to_note(path: Path, source: str) -> Note:
    record = parse_note(path)
    return Note(
        note_name=record.note_name,
        title=record.title,
        source=source,
        outcome=record.outcome,
        kind=record.kind,
        failure_class=record.failure_class,
        tags=tuple(record.tags),
        created=_created(record),
        body=record.body,
    )


def note_paths(root: str | Path, cfg: CoreConfig | None = None) -> list[tuple[Path, str]]:
    """Every indexable note on disk as ``(path, source)``, in a stable order.

    Missing directories are skipped, so a fresh worktree yields an empty corpus
    rather than an error.
    """
    root = Path(root)
    found: list[tuple[Path, str]] = []
    for source, rel in note_sources(cfg):
        directory = root / rel
        if not directory.is_dir():
            continue
        for path in sorted(directory.glob("*.md")):
            if is_indexable(path):
                found.append((path, source))
    return found


def read_notes(root: str | Path, cfg: CoreConfig | None = None) -> list[Note]:
    """Parse the whole vault into notes, sorted by note name (deterministic:
    never dependent on filesystem iteration order)."""
    notes = [_to_note(path, source) for path, source in note_paths(root, cfg)]
    notes.sort(key=lambda n: (n.note_name, n.source))
    return notes


# --- the index ----------------------------------------------------------------

class NoteIndex:
    """A field-weighted BM25 index over the repo's own notes.

    Pure and deterministic: no embeddings, no model call, no wall-clock read.
    Ties break on note name, so every ranking is total and reproducible.
    """

    def __init__(self, notes: list[Note], cfg: RetrievalConfig | None = None) -> None:
        self.notes = list(notes)
        self.cfg = cfg or RetrievalConfig()
        self._tf: list[dict[str, float]] = [self._weighted_tf(n) for n in self.notes]
        self._df: Counter[str] = Counter()
        for tf in self._tf:
            self._df.update(tf.keys())
        lengths = [sum(tf.values()) for tf in self._tf]
        self._avgdl = (sum(lengths) / len(lengths)) if lengths else 0.0
        self._newest = max(
            (d for d in (_as_date(n.created) for n in self.notes) if d), default=None
        )

    def __len__(self) -> int:
        return len(self.notes)

    def _weighted_tf(self, note: Note) -> dict[str, float]:
        """Term frequencies with title and tag hits counted for more than body hits.

        A note is *about* its title: a query matching there is far stronger
        evidence than the same word appearing once deep in a transcript.
        """
        tf: dict[str, float] = {}
        for term in tokenize(note.body):
            tf[term] = tf.get(term, 0.0) + 1.0
        for term in tokenize(note.title):
            tf[term] = tf.get(term, 0.0) + self.cfg.title_boost
        for term in tokenize(" ".join(note.tags)):
            tf[term] = tf.get(term, 0.0) + self.cfg.tag_boost
        return tf

    def _idf(self, term: str) -> float:
        """Robertson IDF, extended to terms the corpus has never seen.

        Those get the LARGEST weight rather than zero, which is what makes
        :meth:`_coverage` honest: vocabulary this repo has never written about is
        the strongest evidence that a candidate is new ground, so it has to
        weigh in the denominator instead of quietly vanishing from it. BM25 is
        unaffected - a term with no postings has tf 0 in every note.
        """
        df = self._df.get(term, 0)
        return math.log(1 + (len(self.notes) - df + 0.5) / (df + 0.5))

    def _bm25(self, i: int, terms: set[str]) -> float:
        """Classic Robertson BM25 over the DISTINCT terms of the query - a query
        here is a whole ticket body, and letting one repeated word outweigh three
        precise ones makes the ranking follow boilerplate instead of substance."""
        tf = self._tf[i]
        dl = sum(tf.values())
        if not dl:
            return 0.0
        norm = _K1 * (1 - _B + _B * dl / self._avgdl) if self._avgdl else _K1
        score = 0.0
        for term in sorted(terms):  # fixed summation order => bit-identical re-runs
            f = tf.get(term, 0.0)
            if not f:
                continue
            score += self._idf(term) * (f * (_K1 + 1)) / (f + norm)
        return score

    def _coverage(self, i: int, terms: set[str]) -> float:
        """How much of the query's informative vocabulary this note already holds.

        Bounded in [0, 1], unlike the BM25 score, so a configured threshold means
        the same thing in a repo with 5 notes and one with 500. Rare terms - up
        to and including ones no note has ever used - dominate the denominator,
        so a candidate is only "already covered" when the words that make it
        specific are the ones this note already contains.
        """
        tf = self._tf[i]
        total = matched = 0.0
        for term in sorted(terms):
            weight = self._idf(term)
            total += weight
            if tf.get(term):
                matched += weight
        return matched / total if total else 0.0

    def _recency(self, note: Note) -> float:
        """Half-life decay against the NEWEST note in the index.

        Measured against the corpus rather than today's date on purpose: the same
        corpus must rank identically tomorrow, next month, and in CI.
        """
        created = _as_date(note.created)
        if created is None or self._newest is None or self.cfg.half_life_days <= 0:
            return 1.0
        age = max((self._newest - created).days, 0)
        return 0.5 ** (age / self.cfg.half_life_days)

    def search(self, query: str, k: int | None = None) -> list[PriorArt]:
        """Rank notes against ``query``, best first."""
        limit = self.cfg.k if k is None else k
        terms = set(tokenize(query))
        if not terms or limit <= 0:
            return []
        hits: list[PriorArt] = []
        for i, note in enumerate(self.notes):
            base = self._bm25(i, terms)
            if base <= 0:
                continue
            hits.append(
                PriorArt(
                    note_name=note.note_name,
                    title=note.title,
                    source=note.source,
                    outcome=note.outcome,
                    failure_class=note.failure_class,
                    # Rounded so float noise can never reorder equal matches.
                    score=round(base * self._recency(note), 6),
                    coverage=round(self._coverage(i, terms), 6),
                )
            )
        hits.sort(key=lambda h: (-h.score, h.note_name))
        return hits[:limit]


# --- the notes.json artifact ---------------------------------------------------

def index_path(root: str | Path, cfg: CoreConfig | None = None) -> Path:
    return Path(root) / RetrievalConfig.from_core(cfg).index_dir / INDEX_FILENAME


def serialize(notes: list[Note]) -> str:
    """The committed index text. Contains no timestamp and no ordering that
    depends on the filesystem, so two runs over unchanged notes are byte-identical."""
    payload = {
        "schema_version": SCHEMA_VERSION,
        "nodes": [n.to_node() for n in notes],
    }
    return json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def deserialize(text: str) -> list[Note]:
    """Notes from index text; an unreadable index yields none, never an exception -
    the caller then rebuilds from the vault."""
    try:
        payload = json.loads(text)
    except (json.JSONDecodeError, TypeError):
        return []
    if not isinstance(payload, dict):
        return []
    return [Note.from_node(n) for n in payload.get("nodes", []) if isinstance(n, dict)]


def write_index(root: str | Path, cfg: CoreConfig | None = None) -> Path:
    """(Re)generate ``knowledge/index/notes.json`` from what is on disk.

    Serialized maintenance, exactly like the MOCs: run from ``hsai reindex`` and
    the cycle's index step, never from a parallel worker, so concurrent PRs
    cannot collide on a shared derived file.
    """
    path = index_path(root, cfg)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(serialize(read_notes(root, cfg)))
    return path


def load_index(root: str | Path, cfg: CoreConfig | None = None) -> NoteIndex:
    """The index to query.

    Prefers the committed ``notes.json``, but only while it still covers exactly
    the notes on disk - a lesson written since the last reindex must never be
    invisible to the planner. Otherwise it rebuilds from the vault in memory,
    leaving the artifact for the serialized maintenance step to refresh.
    """
    rcfg = RetrievalConfig.from_core(cfg)
    path = index_path(root, cfg)
    notes: list[Note] = []
    if path.is_file():
        notes = deserialize(path.read_text())
        on_disk = {p.stem for p, _ in note_paths(root, cfg)}
        if {n.note_name for n in notes} != on_disk:
            notes = []
    if not notes:
        notes = read_notes(root, cfg)
    return NoteIndex(notes, rcfg)


# --- what the planner sees -----------------------------------------------------

def render_prior_art(items: tuple[PriorArt, ...] | list[PriorArt]) -> str:
    """The prompt block: one cited note per line, outcome included."""
    if not items:
        return _EMPTY_PRIOR_ART
    return "\n".join(f"- {p.citation()}" for p in items)


def for_queries(
    index: NoteIndex, queries: list[str] | tuple[str, ...], *, k: int | None = None
) -> tuple[PriorArt, ...]:
    """Top-k notes for each query, merged and deduped, best score first.

    Used to ground a whole cycle: one query per goal, so the planner opens with
    what this repo has already recorded about the ground it is about to plan on.
    """
    best: dict[str, PriorArt] = {}
    for query in queries:
        for hit in index.search(query, k):
            prior = best.get(hit.note_name)
            if prior is None or hit.score > prior.score:
                best[hit.note_name] = hit
    return tuple(sorted(best.values(), key=lambda h: (-h.score, h.note_name)))


@dataclass(frozen=True)
class DuplicateRisk:
    """Does a candidate restate something this repo already tried and failed?"""

    flagged: bool = False
    note_name: str = ""
    title: str = ""
    outcome: str = "unknown"
    coverage: float = 0.0

    @property
    def decision(self) -> str:
        """What synthesis does with the candidate - the half that gets recorded."""
        return "drop" if self.flagged else "keep"

    def render(self, candidate: str) -> str:
        """One auditable line: the candidate, the flag, and the decision."""
        if not self.note_name:
            return f"{candidate} -> keep (no prior art matched)"
        why = "restates a FAILED note" if self.flagged else "closest prior art"
        return (
            f"{candidate} -> {self.decision} ({why}: [[{self.note_name}]] "
            f"outcome={self.outcome}, coverage={self.coverage:.2f})"
        )


def duplicate_risk(
    index: NoteIndex, text: str, *, threshold: float | None = None, k: int | None = None
) -> DuplicateRisk:
    """Flag a candidate whose prior art is a lesson that already failed.

    Pure and side-effect free. Three conditions, all required: the candidate is
    described in at least ``min_query_terms`` distinct words (less than that and
    coverage measures nothing), the match is a note whose recorded outcome is
    ``fail``, and its coverage of the candidate's informative vocabulary is at
    or above ``threshold``. The whole top-k window is scanned, not just the
    single best score - a failed lesson can rank second on BM25 and still be
    exactly the idea being re-proposed.

    An unflagged result still names the closest note, so "keep" is as
    explainable as "drop".
    """
    hits = index.search(text, index.cfg.k if k is None else k)
    if not hits:
        return DuplicateRisk()
    limit = index.cfg.duplicate_threshold if threshold is None else threshold
    described = len(set(tokenize(text))) >= index.cfg.min_query_terms
    failed = [h for h in hits if described and h.outcome == "fail" and h.coverage >= limit]
    if failed:
        worst = sorted(failed, key=lambda h: (-h.coverage, -h.score, h.note_name))[0]
        return DuplicateRisk(
            flagged=True, note_name=worst.note_name, title=worst.title,
            outcome=worst.outcome, coverage=worst.coverage,
        )
    top = hits[0]
    return DuplicateRisk(
        flagged=False, note_name=top.note_name, title=top.title,
        outcome=top.outcome, coverage=top.coverage,
    )


def resolve_citations(
    index: NoteIndex, cited: tuple[str, ...] | list[str], query: str, *, k: int | None = None
) -> tuple[str, ...]:
    """Citation-grade prior art for one ticket.

    The model's own citations are honoured only when the note actually exists in
    the index - a wikilink that resolves to nothing would break the Obsidian
    graph and fake the provenance - and deterministic top-k retrieval over
    ``query`` fills the rest.
    """
    known = {n.note_name: n for n in index.notes}
    citations: list[str] = []
    seen: set[str] = set()
    for raw in cited:
        name = _WIKILINK_RE.sub(r"\1", str(raw).strip()).strip()
        note = known.get(name)
        if note is not None and note.note_name not in seen:
            seen.add(note.note_name)
            citations.append(cite(note))
    for hit in index.search(query, k):
        if hit.note_name not in seen:
            seen.add(hit.note_name)
            citations.append(hit.citation())
    return tuple(citations)
