"""Workflow change proposal protocol.

The orchestrator is forbidden from changing CI workflows (orchestrator.run_once
reverts any .github/workflows/** edits) because a worker that edits its own CI
checks could weaken them without oversight - breaking a core invariant.

This module provides a supervised channel: propose_workflow_change() captures
the intent as a human-readable proposal file instead of silently discarding it.
A human then applies the proposal through the review-next rhythm, so CI changes
are auditable and intentional.

This supports G2 (auditability) by making workflow evolution explicit, and G4
(harness self-improvement) by enabling the loop to propose its own CI changes.
"""
from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


def check_documented_gates(sdlc_text: str, workflow_yaml: str) -> list[str]:
    """Find status checks named in SDLC docs but missing from the workflow.

    Args:
        sdlc_text: The full text of docs/SDLC.md
        workflow_yaml: The full text of .github/workflows/ci.yml

    Returns:
        List of status check names documented but not enforced in the workflow.
        Empty list if all documented checks are present.

    Example:
        If SDLC.md says "Required `ci` + `repro-guard` status checks" but
        ci.yml only defines the `ci` job, returns ["repro-guard"].
    """
    # Extract job names from the workflow YAML.
    # Looks for lines like "  ci:" or "  repro-guard:" under the jobs section.
    job_pattern = re.compile(r"^\s{2}(\w+):\s*$", re.MULTILINE)
    workflow_jobs = set(job_pattern.findall(workflow_yaml))

    # Extract status checks mentioned in the SDLC as "Required `x` + `y`".
    # Matches inline code blocks in the required checks context.
    check_pattern = re.compile(r"Required\s+(.+?)(?:\s+status checks|\s*$)", re.IGNORECASE)
    match = check_pattern.search(sdlc_text)
    if not match:
        return []

    check_str = match.group(1)
    # Extract all backtick-quoted names like `ci` or `repro-guard`
    documented_checks = re.findall(r"`(\w+(?:-\w+)*)`", check_str)

    missing = [check for check in documented_checks if check not in workflow_jobs]
    return sorted(set(missing))


def propose_workflow_change(
    patch: str,
    reason: str,
    *,
    repo_root: str | Path,
) -> Path:
    """Capture a workflow change as a dated proposal file.

    Called by orchestrator.run_once when it reverts a .github/workflows/**
    edit. Instead of silently discarding the intent, we write a human-readable
    proposal file that can be applied through the review-next rhythm.

    Args:
        patch: The unified diff of the proposed change (from git diff, etc).
        reason: Why this change is needed (citation from the lesson, etc).
        repo_root: The repository root.

    Returns:
        Path to the written proposal file under governance/proposed-workflows/.

    Example:
        A worker edits .github/workflows/ci.yml to add a `repro-guard` job.
        The orchestrator reverts it, then calls propose_workflow_change() with
        the diff. The proposal lands at:
            governance/proposed-workflows/2026-08-07T10-32-45Z_split_ci_jobs.md
    """
    root = Path(repo_root)
    proposals_dir = root / "governance" / "proposed-workflows"
    proposals_dir.mkdir(parents=True, exist_ok=True)

    # Timestamp in ISO 8601 format, with hyphens for filesystem-safe use
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H-%M-%SZ")
    # Extract a slug from the reason (first few words after "refactor:" or similar)
    slug_match = re.search(r"(?:split|add|refactor|update)[\s:]+([a-z0-9_]+)", reason, re.IGNORECASE)
    slug = slug_match.group(1) if slug_match else "proposal"
    filename = f"{now}_{slug}.md"
    proposal_path = proposals_dir / filename

    # Render as markdown so it is readable in GitHub diffs and reviews
    content = f"""# Workflow Proposal

**Timestamp:** {now}

**Reason:**
{reason}

## Proposed Change

```diff
{patch}
```

---

This proposal was generated by the hsai loop when a workflow edit was reverted.
To apply it, review the diff above and merge this file's content into the target
workflow file, then commit under governance/. See docs/SDLC.md phase 4 for the
workflow change review protocol.
"""
    proposal_path.write_text(content)
    return proposal_path


def list_proposed_changes(repo_root: str | Path) -> list[Path]:
    """Find all pending workflow change proposals.

    Returns proposal files under governance/proposed-workflows/ sorted by
    timestamp (newest first), so they can be walked in order during review.
    """
    root = Path(repo_root)
    proposals_dir = root / "governance" / "proposed-workflows"
    if not proposals_dir.exists():
        return []
    # Sort by filename (which embeds the timestamp) in reverse order
    return sorted(proposals_dir.glob("*.md"), reverse=True)


def render_proposed_workflows_section(repo_root: str | Path) -> str:
    """Render a markdown section listing pending workflow proposals.

    Used by governance.render_brief to show the architect which workflow
    changes are pending review.

    Returns:
        Markdown section (possibly empty if no proposals pending).
    """
    proposals = list_proposed_changes(repo_root)
    if not proposals:
        return "_none - all workflow proposals have been applied_"
    lines = [
        f"- `{p.name}` ([[propose-{p.stem}]])"
        for p in proposals
    ]
    return "\n".join(lines)
